@ECHO Installing required packages for Buy-Bot...

@ECHO Installing Selenium...
cmd /c "pip install selenium"

@ECHO Installing dotENV...
cmd /c "pip install python-dotenv"

@ECHO Installing asyncIO...
cmd /c "pip install asyncio"

@ECHO Process finished. Please edit .env file before running start.bat  
@pause